/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.curso.kafka.avro.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Clima extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7473780684719065499L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Clima\",\"namespace\":\"com.curso.kafka.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"datos\",\"type\":{\"type\":\"record\",\"name\":\"Datos\",\"fields\":[{\"name\":\"temp\",\"type\":\"float\"},{\"name\":\"presion\",\"type\":\"int\"},{\"name\":\"humedad\",\"type\":\"int\"},{\"name\":\"tempMin\",\"type\":\"float\"},{\"name\":\"tempMax\",\"type\":\"float\"}]}},{\"name\":\"detalles\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Detalles\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"principal\",\"type\":\"string\"},{\"name\":\"descripcion\",\"type\":\"string\"},{\"name\":\"icono\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Clima> ENCODER =
      new BinaryMessageEncoder<Clima>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Clima> DECODER =
      new BinaryMessageDecoder<Clima>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Clima> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Clima> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Clima> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Clima>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Clima to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Clima from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Clima instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Clima fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.lang.CharSequence nombre;
   private com.curso.kafka.avro.model.Datos datos;
   private java.util.List<com.curso.kafka.avro.model.Detalles> detalles;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Clima() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param nombre The new value for nombre
   * @param datos The new value for datos
   * @param detalles The new value for detalles
   */
  public Clima(java.lang.Long id, java.lang.CharSequence nombre, com.curso.kafka.avro.model.Datos datos, java.util.List<com.curso.kafka.avro.model.Detalles> detalles) {
    this.id = id;
    this.nombre = nombre;
    this.datos = datos;
    this.detalles = detalles;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return nombre;
    case 2: return datos;
    case 3: return detalles;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: nombre = (java.lang.CharSequence)value$; break;
    case 2: datos = (com.curso.kafka.avro.model.Datos)value$; break;
    case 3: detalles = (java.util.List<com.curso.kafka.avro.model.Detalles>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'datos' field.
   * @return The value of the 'datos' field.
   */
  public com.curso.kafka.avro.model.Datos getDatos() {
    return datos;
  }


  /**
   * Sets the value of the 'datos' field.
   * @param value the value to set.
   */
  public void setDatos(com.curso.kafka.avro.model.Datos value) {
    this.datos = value;
  }

  /**
   * Gets the value of the 'detalles' field.
   * @return The value of the 'detalles' field.
   */
  public java.util.List<com.curso.kafka.avro.model.Detalles> getDetalles() {
    return detalles;
  }


  /**
   * Sets the value of the 'detalles' field.
   * @param value the value to set.
   */
  public void setDetalles(java.util.List<com.curso.kafka.avro.model.Detalles> value) {
    this.detalles = value;
  }

  /**
   * Creates a new Clima RecordBuilder.
   * @return A new Clima RecordBuilder
   */
  public static com.curso.kafka.avro.model.Clima.Builder newBuilder() {
    return new com.curso.kafka.avro.model.Clima.Builder();
  }

  /**
   * Creates a new Clima RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Clima RecordBuilder
   */
  public static com.curso.kafka.avro.model.Clima.Builder newBuilder(com.curso.kafka.avro.model.Clima.Builder other) {
    if (other == null) {
      return new com.curso.kafka.avro.model.Clima.Builder();
    } else {
      return new com.curso.kafka.avro.model.Clima.Builder(other);
    }
  }

  /**
   * Creates a new Clima RecordBuilder by copying an existing Clima instance.
   * @param other The existing instance to copy.
   * @return A new Clima RecordBuilder
   */
  public static com.curso.kafka.avro.model.Clima.Builder newBuilder(com.curso.kafka.avro.model.Clima other) {
    if (other == null) {
      return new com.curso.kafka.avro.model.Clima.Builder();
    } else {
      return new com.curso.kafka.avro.model.Clima.Builder(other);
    }
  }

  /**
   * RecordBuilder for Clima instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Clima>
    implements org.apache.avro.data.RecordBuilder<Clima> {

    private long id;
    private java.lang.CharSequence nombre;
    private com.curso.kafka.avro.model.Datos datos;
    private com.curso.kafka.avro.model.Datos.Builder datosBuilder;
    private java.util.List<com.curso.kafka.avro.model.Detalles> detalles;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.curso.kafka.avro.model.Clima.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.datos)) {
        this.datos = data().deepCopy(fields()[2].schema(), other.datos);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasDatosBuilder()) {
        this.datosBuilder = com.curso.kafka.avro.model.Datos.newBuilder(other.getDatosBuilder());
      }
      if (isValidValue(fields()[3], other.detalles)) {
        this.detalles = data().deepCopy(fields()[3].schema(), other.detalles);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Clima instance
     * @param other The existing instance to copy.
     */
    private Builder(com.curso.kafka.avro.model.Clima other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nombre)) {
        this.nombre = data().deepCopy(fields()[1].schema(), other.nombre);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.datos)) {
        this.datos = data().deepCopy(fields()[2].schema(), other.datos);
        fieldSetFlags()[2] = true;
      }
      this.datosBuilder = null;
      if (isValidValue(fields()[3], other.detalles)) {
        this.detalles = data().deepCopy(fields()[3].schema(), other.detalles);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nombre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'datos' field.
      * @return The value.
      */
    public com.curso.kafka.avro.model.Datos getDatos() {
      return datos;
    }


    /**
      * Sets the value of the 'datos' field.
      * @param value The value of 'datos'.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder setDatos(com.curso.kafka.avro.model.Datos value) {
      validate(fields()[2], value);
      this.datosBuilder = null;
      this.datos = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'datos' field has been set.
      * @return True if the 'datos' field has been set, false otherwise.
      */
    public boolean hasDatos() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'datos' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.curso.kafka.avro.model.Datos.Builder getDatosBuilder() {
      if (datosBuilder == null) {
        if (hasDatos()) {
          setDatosBuilder(com.curso.kafka.avro.model.Datos.newBuilder(datos));
        } else {
          setDatosBuilder(com.curso.kafka.avro.model.Datos.newBuilder());
        }
      }
      return datosBuilder;
    }

    /**
     * Sets the Builder instance for the 'datos' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.curso.kafka.avro.model.Clima.Builder setDatosBuilder(com.curso.kafka.avro.model.Datos.Builder value) {
      clearDatos();
      datosBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'datos' field has an active Builder instance
     * @return True if the 'datos' field has an active Builder instance
     */
    public boolean hasDatosBuilder() {
      return datosBuilder != null;
    }

    /**
      * Clears the value of the 'datos' field.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder clearDatos() {
      datos = null;
      datosBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'detalles' field.
      * @return The value.
      */
    public java.util.List<com.curso.kafka.avro.model.Detalles> getDetalles() {
      return detalles;
    }


    /**
      * Sets the value of the 'detalles' field.
      * @param value The value of 'detalles'.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder setDetalles(java.util.List<com.curso.kafka.avro.model.Detalles> value) {
      validate(fields()[3], value);
      this.detalles = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'detalles' field has been set.
      * @return True if the 'detalles' field has been set, false otherwise.
      */
    public boolean hasDetalles() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'detalles' field.
      * @return This builder.
      */
    public com.curso.kafka.avro.model.Clima.Builder clearDetalles() {
      detalles = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Clima build() {
      try {
        Clima record = new Clima();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.nombre = fieldSetFlags()[1] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (datosBuilder != null) {
          try {
            record.datos = this.datosBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("datos"));
            throw e;
          }
        } else {
          record.datos = fieldSetFlags()[2] ? this.datos : (com.curso.kafka.avro.model.Datos) defaultValue(fields()[2]);
        }
        record.detalles = fieldSetFlags()[3] ? this.detalles : (java.util.List<com.curso.kafka.avro.model.Detalles>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Clima>
    WRITER$ = (org.apache.avro.io.DatumWriter<Clima>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Clima>
    READER$ = (org.apache.avro.io.DatumReader<Clima>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.nombre);

    this.datos.customEncode(out);

    long size0 = this.detalles.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.curso.kafka.avro.model.Detalles e0: this.detalles) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      if (this.datos == null) {
        this.datos = new com.curso.kafka.avro.model.Datos();
      }
      this.datos.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<com.curso.kafka.avro.model.Detalles> a0 = this.detalles;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.curso.kafka.avro.model.Detalles>((int)size0, SCHEMA$.getField("detalles").schema());
        this.detalles = a0;
      } else a0.clear();
      SpecificData.Array<com.curso.kafka.avro.model.Detalles> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.curso.kafka.avro.model.Detalles>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.curso.kafka.avro.model.Detalles e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.curso.kafka.avro.model.Detalles();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 2:
          if (this.datos == null) {
            this.datos = new com.curso.kafka.avro.model.Datos();
          }
          this.datos.customDecode(in);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<com.curso.kafka.avro.model.Detalles> a0 = this.detalles;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.curso.kafka.avro.model.Detalles>((int)size0, SCHEMA$.getField("detalles").schema());
            this.detalles = a0;
          } else a0.clear();
          SpecificData.Array<com.curso.kafka.avro.model.Detalles> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.curso.kafka.avro.model.Detalles>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.curso.kafka.avro.model.Detalles e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.curso.kafka.avro.model.Detalles();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










