version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    network_mode: host
  kafka1:
    image: 'bitnami/kafka:latest'
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://192.168.50.15:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://migateway:9092
      - KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:latest'
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=PLAINTEXT://192.168.50.16:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://migateway:9192
      - KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:latest'
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=PLAINTEXT://192.168.50.17:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://migateway:9292
      - KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  schema_registry:
    image: confluentinc/cp-schema-registry:6.0.0
    network_mode: host
    environment: 
      - "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=localhost:9091,localhost:9092,localhost:9093"
      - "SCHEMA_REGISTRY_HOST_NAME=localhost"
    depends_on: 
      - kafka1
      - kafka2
      - kafka3