services: 
  zookeeper:
    container_name: zookeeper
    build:
      context: .
    command: ['/kafka/bin/zookeeper-server-start.sh','/config/zookeeper.properties']
    volumes:
      - ./config:/config
      - ./data/zookeeper:/zookeeper
  broker1:
    container_name: broker1
    build:
      context: .
    depends_on:
      - zookeeper
    command: ['/kafka/bin/kafka-server-start.sh','/config/broker1.properties']
    ports:
      - 29092:29092
    volumes:
      - ./config:/config
      - ./data/broker1:/kafka-logs

  broker2:
    container_name: broker2
    build:
      context: .
    depends_on:
      - zookeeper
    command: ['/kafka/bin/kafka-server-start.sh','/config/broker2.properties']
    ports:
      - 29093:29093
    volumes:
      - ./config:/config
      - ./data/broker2:/kafka-logs      

  broker3:
    container_name: broker3
    build:
      context: .
    depends_on:
      - zookeeper
    command: ['/kafka/bin/kafka-server-start.sh','/config/broker3.properties']
    ports:
      - 29094:29094
    volumes:
      - ./config:/config
      - ./data/broker3:/kafka-logs

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker1:9092,broker2:9092,broker3:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081